name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        compiler: [gcc, clang, msvc]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y cmake g++

    - name: Install dependencies on macOS
      if: matrix.os == 'macos-latest'
      run: brew install cmake

    - name: Install dependencies on Windows
      if: matrix.os == 'windows-latest'
      run: choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"'

    - name: Create build directory
      run: mkdir build

    - name: Configure with CMake
      working-directory: ./build
      run: cmake -DCMAKE_BUILD_TYPE=Debug ..

    - name: Build
      working-directory: ./build
      run: cmake --build . --config Debug

    - name: Run tests
      working-directory: ./build
      run: ctest -C Debug --output-on-failure
