name: Code Quality and Linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y clang-tidy python3-pip

    - name: Install cpplint
      run: pip3 install cpplint

    - name: Run clang-tidy
      run: |
        find . -name "*.cpp" | xargs clang-tidy --quiet

    - name: Run cpplint
      run: |
        find . -name "*.cpp" -or -name "*.hpp" | xargs cpplint
