name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 1' # Run every Monday

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh

    - name: Install Dependencies
      run: ./vcpkg/vcpkg install

    - name: Run Dependency Report
      run: ./vcpkg/vcpkg list
