name: Generate Doxygen Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget

    - name: Install Latest Doxygen
      run: |
        wget -O doxygen.tar.gz https://doxygen.nl/files/doxygen-1.9.8.linux.bin.tar.gz
        tar -xzf doxygen.tar.gz
        sudo mv doxygen-1.9.8/bin/* /usr/local/bin/
        doxygen --version

    - name: Create Output Directory
      run: mkdir -p docs/doxygen

    - name: Generate Documentation
      run: doxygen Doxyfile

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/doxygen/html
