name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/*  #
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
