name: Mark Stale Issues and PRs

on:
  schedule:
    - cron: '0 0 * * *' # Run daily

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
    - name: Mark stale issues and PRs
      uses: actions/stale@v7
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been marked as stale due to inactivity.'
        stale-pr-message: 'This PR has been marked as stale due to inactivity.'
        days-before-stale: 30
        days-before-close: 7
